### Group Members:

- Name, matriculation number
- Name, matriculation number
- Name, matriculation number

# Assignment 2: Gradient Descent

The goal of this exercise is to gain experience with a basic technique of Deep Learning, i.e., gradient descent.
A two-dimensional loss surface is created manually and gradient descent is implemented.
Several runs of gradient descent from different starting locations will be performed.
The loss surface and the detected minima are plotted together in one 3D plot.

## Compute the Gradient
The loss function is manually defined as $$\mathcal J_{\vec w}=40 \sin^3\left(\frac{1}{2}w_1+ w_2\right) + w_1^2 + w_2^2$$
The weights $\vec w = (w_1, w_2)^T$ shall be optimized such that the loss function has a minimum.

### Task 1: Compute the Gradient

The gradient $\nabla \mathcal J_{\vec w}$ is defined as the partial derivatives of the loss function with respect to the two variables $w_1$ and $w_2$.
We need to calculate it:

* $\frac{\partial \mathcal J}{\partial w_1} = ...$
* $\frac{\partial \mathcal J}{\partial w_2} = ...$

### Task 2: Implement the Loss Function

Implement the loss function in Python, which takes a given $\vec w$ and returns $\mathcal J_{\vec w}$ according to the given loss function.

In [36]:
import numpy
import numpy as np

def loss(w):
  return 40*np.power(np.sin(0.5*w[0]+w[1]),3)+w[0]**2+w[1]**2

### Task 3: Implement the Gradient

Implement the gradient as a function in Python, which takes a given $\vec w$ and returns $\nabla\mathcal J_{\vec w}$ according to the analytical result in Task 1.
Remember that the gradient needs to be computed and returned for both $w_1$ and $w_2$.

In [56]:
def gradient(w):
  return np.array([60*np.power(np.sin(0.5*w[0]+w[1]),2)*np.cos(0.5*w[0]+w[1])+2*w[0], 120*np.power(np.sin(0.5*w[0]+w[1]),2)*np.cos(0.5*w[0]+w[1])+2*w[1]])

### Test 1: Test Functions
The codes below call the loss function from Task 2 and the gradient function from Task 3 with $\vec w=(0,0)^T$ and then compare the return values with the given analytically computed values.
Please check your implementation if the tests cannot be passed.

Make sure your code can pass the test before moving to the next task.

In [57]:
w = numpy.zeros(2)

# analytically compute the expected values
expected_loss = 0.
expected_gradient = numpy.array((0.,0.))

# test loss function
assert abs(loss(w) - expected_loss) < 1e-8
assert numpy.all(numpy.abs(gradient(w) - expected_gradient) < 1e-8)
print("Tests passed")

Tests passed


## Implement Gradient Descent
The procedure of gradient decent is the repeated application of two steps:

* First, the gradient of the loss $\nabla\mathcal J_{\vec w}$ is computed based on the current value of the parameters $\vec w$.

* Second, the weights are updated by moving a small step in the direction of the negative gradient: $\vec w = \vec w - \eta\nabla\mathcal J_{\vec w}$

Optionally, the loss $\mathcal J_{\vec w}$ is computed to record the progress of the gradient descent.
Finally, one or more appropriate criteria need to be defined to decide when to stop the procedure.

### Task 4: Termination Criterion

(theoretical question) Define a proper termination criterion. Which error cases might occur and need to be considered?

We could decide to stop after a predefined number of iterations. A problem is that we could not get to the minima (saddle point or local minima).

### Task 5: Implement Gradient Descent

Implement a function that performs the gradient descent. This function should take as parameters an initial weight vector $\vec w$ and a learning rate $\eta$, and make use of the gradient function implemented in Task 3 and, possibly, the loss function from Task 2.
It should return the optimized weight vector $\vec w^*$. Incorporate the termination criterion designed in Task 4.

In [72]:
def gradient_descent(w, eta=0.01):
  # copy the weights to not modify the original values
  w_star = w.copy()

  # perform iterative gradient descent
  while True:
    # compute the gradient
    w_prev = w_star.copy()
    grad = gradient(w_star)

    # update the weights
#     update_candidate = w_star - eta*grad
#     loss_diff = loss(update_candidate)-loss(w_star)
#     if loss_diff < 0:
#         w_star = update_candidate
#         eta = 1.1*eta
#     else:
#         eta = 0.5*eta
    #print(w_star)
    w_star = w_star-eta*grad

    # include additional termination criteria?
    if np.linalg.norm(w_star-w_prev) < 1e-8:
        break
        
  return w_star

## Evaluate Gradient Descent

### Task 6: Evaluate Gradient Descent
Call the gradient descent function from Task 5 1000 times with different random initialized weights $\vec w\in[-10,10]^2$ and a learning rate of $\eta=0.01$. Store the resulting optimized weight vectors in a list.

In [73]:
from tqdm import tqdm

stored_weights = []

for i in tqdm(range(1000)):
  # create random weight vector
  w = np.random.uniform(low=-10, high=10, size=(2,))
  #print(w)
  # call gradient descent
  w_star = gradient_descent(w)
  #print(w_star)
  # store it in the list
  stored_weights.append(w_star)

### Test 2: Check Minima

Counting the number of local minima in our loss function, we reach a total of 11. Please use this function to verify that your implementation could reach this number at maximum.

Again, make sure you pass the test before moving to the next task.

In [75]:
maximum_number_of_minima = 11

# compute the number of reached minima
minima = []
for w_star in stored_weights:
  # check if this weight vector is far enough
  # from all previously stored vectors
  # print(numpy.linalg.norm(w_star-w))  
  if all(numpy.linalg.norm(w_star-w) > 1e-3 for w in minima):
    minima.append(w_star)
number_of_minima = len(minima)
#print(len(minima))
#print(maximum_number_of_minima)

assert number_of_minima <= maximum_number_of_minima

print("Check passed. The number of minima", number_of_minima, "is lower than or equal to the maximum", maximum_number_of_minima)

Check passed. The number of minima 11 is lower than or equal to the maximum 11


In [76]:
stored_weights

[array([-3.09973097, -6.19946086]),
 array([1.86004204, 3.72008515]),
 array([-3.09973097, -6.19946086]),
 array([-4.34691037e-07,  2.18053697e-07]),
 array([1.86004203, 3.72008515]),
 array([-3.09973011, -6.19946129]),
 array([-0.62004754, -1.240094  ]),
 array([-3.09973097, -6.19946086]),
 array([ -5.57713676, -11.15427244]),
 array([-3.09973011, -6.19946129]),
 array([1.86004203, 3.72008515]),
 array([-0.62004668, -1.24009444]),
 array([-3.09973011, -6.19946129]),
 array([-0.62004667, -1.24009444]),
 array([-3.09973097, -6.19946086]),
 array([1.86004203, 3.72008515]),
 array([1.8600429 , 3.72008472]),
 array([-2.39607053, -4.79214214]),
 array([-2.3960714, -4.7921417]),
 array([-3.09973097, -6.19946086]),
 array([-0.62004668, -1.24009444]),
 array([1.8600429 , 3.72008472]),
 array([4.33886783, 8.67773459]),
 array([-3.09973011, -6.19946129]),
 array([-3.09973097, -6.19946086]),
 array([4.33886784, 8.67773459]),
 array([4.33886784, 8.67773459]),
 array([3.62271042, 7.24541975]),
 arr

### Task 7: Find the Global Minimum

Find the global minimum of our error function by evaluating the obtained optimized weight vectors from Task 6.
Print the minimum and its loss value.

In [ ]:
# find the lowest loss
min = w[0]
for w in stored_weights:
    if np.linalg.norm(w[0])
minimum_loss = 
minimum_weights = ...

print("The minimum loss value of:", minimum_loss, "was found for minimum", minimum_weights)

## Plot Error Surface and Points

### Task 8: Loss Surface Plot

Plot the error surface of the given loss function. Limit range $\vec w\in[-20,20]^2$. For each of the optimized weights from Task 6, plot a marker into the 3D plot. An example can be found in the slides.

When plotting the resulting optimized weights $\vec w=(w_1, w_2)^T$, we need to define the third coordinate. What should this coordinate be?


In [ ]:
from matplotlib import pyplot

# create 3D axis
figure = pyplot.figure()
axis = figure.add_subplot(111, projection='3d', azim = -40, elev=50)

# define range to plot
w_range = ...
w1, w2 = numpy.meshgrid(w_range, w_range)

# compute loss for w1 and w2
J = ...

# plot surface with jet colormap
axis.plot_surface(w1, w2, J, cmap="jet", alpha=0.7)

# plot resulting points in 3D
for w_star in stored_weights:
  # compute the z-position
  z = ...
  # plot as 3D point
  axis.plot([w_star[0]], [w_star[1]], [z], "kx")